In [1]:
import cv2
import numpy as np
import glob

# 设置棋盘格角点数量 (9x7)
# 对于一个10x8的棋盘格，应该设置棋盘格角点为(9, 7)，因为在一个由10个格（5个黑5个白）组成的行中，有9个内角点，同理列中有7个内角点。
checkerboard_size = (9, 7)

# 准备对象点，如 (0,0,0), (1,0,0), ..., (8,6,0)
objp = np.zeros((checkerboard_size[0] * checkerboard_size[1], 3), np.float32)
objp[:,:2] = np.mgrid[0:checkerboard_size[0],0:checkerboard_size[1]].T.reshape(-1,2)

# 用于存储所有图片的对象点和角点的数组
objpoints = [] # 真实世界中的点
imgpoints = [] # 图像中的点

# 获取标定图片路径
images = glob.glob('./calibration_images/*.jpg')

for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # 找到棋盘格角点
    ret, corners = cv2.findChessboardCorners(gray, (checkerboard_size[0], checkerboard_size[1]), None)
    
    # 如果找到足够点对，将其存储起来
    if ret == True:
        objpoints.append(objp)
        corners2 = cv2.cornerSubPix(gray,corners, (11,11), (-1,-1), criteria=(cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001))
        imgpoints.append(corners2)

        # 绘制并显示角点
        img = cv2.drawChessboardCorners(img, (checkerboard_size[0], checkerboard_size[1]), corners2, ret)
        cv2.imshow('img', img)
        cv2.waitKey(500)

cv2.destroyAllWindows()

# 标定
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

# 输出结果
print("相机矩阵:\n", mtx)
print("畸变系数:\n", dist)
print("旋转向量:\n", rvecs)
print("平移向量:\n", tvecs)

相机矩阵:
 [[822.41557991   0.         321.98439837]
 [  0.         822.15932859 237.94729242]
 [  0.           0.           1.        ]]
畸变系数:
 [[ 5.64451053e-02 -1.87491584e-02 -2.69532797e-03  5.18462008e-04
   1.92372594e+00]]
旋转向量:
 (array([[-0.01652157],
       [-0.08661379],
       [-0.01978376]]), array([[-0.50029971],
       [ 0.13664547],
       [ 2.97872589]]), array([[-0.30888317],
       [ 0.84652581],
       [ 2.25920711]]), array([[-1.16954358],
       [-0.07825485],
       [-0.0626217 ]]), array([[-0.46535496],
       [ 0.7324361 ],
       [ 2.15365424]]), array([[0.06687471],
       [1.30931468],
       [2.78399371]]), array([[-0.39520545],
       [-1.19824819],
       [-2.32477846]]), array([[-0.83602715],
       [ 0.64466452],
       [ 1.06734949]]), array([[-1.03454892],
       [ 0.09527891],
       [ 0.13987295]]), array([[-0.48562079],
       [-0.03360511],
       [-0.0111058 ]]), array([[ 0.1553032 ],
       [-0.71145743],
       [ 3.01637061]]), array([[ 0.4758093 ]